version: "2"
services:
  app:
    container_name: touney_backend
    restart: unless-stopped
    build:
      context: .
      args:
        dbConnectionString: 'mongodb://mongo'
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    restart: unless-stopped
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
