server:
  servlet:
    context-path: "/api"
  port: 34345

spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DB_CONNECTION_STRING}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  swagger:
    user: ${SWAGGER_USER}
    password: ${SWAGGER_PASSWORD}
