server:
  servlet:
    context-path: "/api"
  port: 34345

spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true
  swagger:
    user: ${SWAGGER_USER}
    password: ${SWAGGER_PASSWORD}
